#!/usr/bin/env bash
# Bootstrap HashiCorp Vault on a fresh Linux instance (Ubuntu/Debian).
# Matches a typical setup: Raft integrated storage, listener on :8200, TLS disabled on Vault
# (TLS terminated at nginx LB — see node-5/nginx/hash-vault-lb.conf).
#
# Usage (run as root):
#   export VAULT_NODE_ID="vault-4"
#   export VAULT_API_ADDR="http://THIS_NODE_PUBLIC_IP:8200"
#   export VAULT_CLUSTER_ADDR="http://THIS_NODE_PRIVATE_IP:8201"
#   # First node only — omit RAFT_RETRY_JOIN:
#   ./bootstrap-vault-node.sh
#   # Additional nodes — point at existing Raft peers:
#   export RAFT_RETRY_JOIN="http://129.212.216.181:8200 http://129.212.210.167:8200"
#   ./bootstrap-vault-node.sh
#
# After install:
#   First cluster:  vault operator init  (save keys securely; never in user-data)
#   Joined node:    usually comes up sealed; unseal with existing keys or auto-unseal

set -euo pipefail

VAULT_VERSION="${VAULT_VERSION:-1.16.2}"
VAULT_NODE_ID="${VAULT_NODE_ID:?Set VAULT_NODE_ID (e.g. vault-4)}"
VAULT_RAFT_PATH="${VAULT_RAFT_PATH:-/opt/vault/data}"
LISTEN_ADDRESS="${LISTEN_ADDRESS:-0.0.0.0:8200}"
TLS_DISABLE="${TLS_DISABLE:-true}"

# Required for Raft: must be URLs this node and peers can use
VAULT_API_ADDR="${VAULT_API_ADDR:?Set VAULT_API_ADDR e.g. http://203.0.113.10:8200}"
VAULT_CLUSTER_ADDR="${VAULT_CLUSTER_ADDR:?Set VAULT_CLUSTER_ADDR e.g. http://10.0.0.5:8201}"

RAFT_RETRY_JOIN="${RAFT_RETRY_JOIN:-}" # space-separated leader_api_addr URLs

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "Run as root (sudo)." >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends ca-certificates curl gnupg lsb-release

# HashiCorp APT repo (Debian/Ubuntu)
install -d -m 0755 /etc/apt/keyrings
curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /etc/apt/keyrings/hashicorp-archive-keyring.gpg
chmod a+r /etc/apt/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
  > /etc/apt/sources.list.d/hashicorp.list
apt-get update -y
# Exact package version string differs by distro (e.g. 1.16.2-1); pick newest matching $VAULT_VERSION
VAULT_PKG="$(apt-cache madison vault 2>/dev/null | awk -v ver="$VAULT_VERSION" '$3 ~ "^"ver"-" {print $3; exit}')"
if [[ -n "${VAULT_PKG:-}" ]]; then
  apt-get install -y "vault=${VAULT_PKG}"
else
  echo "Warning: apt has no vault=${VAULT_VERSION}-*; installing latest vault from repo" >&2
  apt-get install -y vault
fi

install -d -m 0750 -o vault -g vault "${VAULT_RAFT_PATH}"

HCL="/etc/vault.d/vault.hcl"
umask 027
{
  echo "# Generated by bootstrap-vault-node.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo 'disable_mlock = true'
  echo 'ui            = true'
  echo
  echo 'storage "raft" {'
  echo "  path    = \"${VAULT_RAFT_PATH}\""
  echo "  node_id = \"${VAULT_NODE_ID}\""
  if [[ -n "${RAFT_RETRY_JOIN}" ]]; then
    for leader in ${RAFT_RETRY_JOIN}; do
      echo '  retry_join {'
      echo "    leader_api_addr = \"${leader}\""
      echo '  }'
    done
  fi
  echo '}'
  echo
  echo 'listener "tcp" {'
  echo "  address         = \"${LISTEN_ADDRESS}\""
  echo "  tls_disable     = ${TLS_DISABLE}"
  echo '}'
  echo
  echo "api_addr     = \"${VAULT_API_ADDR}\""
  echo "cluster_addr = \"${VAULT_CLUSTER_ADDR}\""
} > "${HCL}"
chown root:vault "${HCL}"
chmod 0640 "${HCL}"

systemctl daemon-reload
systemctl enable vault
systemctl restart vault

sleep 2
if systemctl is-active --quiet vault; then
  echo "Vault service is active."
else
  echo "Vault failed to start. Check: journalctl -u vault -b" >&2
  exit 1
fi

echo
echo "=== Next steps ==="
if [[ -z "${RAFT_RETRY_JOIN}" ]]; then
  echo "New Raft cluster (first node):"
  echo "  export VAULT_ADDR=${VAULT_API_ADDR}"
  echo "  vault status"
  echo "  vault operator init    # stores keys — protect them; use Shamir or KMS in production"
else
  echo "Joined Raft cluster; node usually starts sealed:"
  echo "  export VAULT_ADDR=${VAULT_API_ADDR}"
  echo "  vault status"
  echo "  vault operator unseal   # or rely on auto-unseal if configured"
fi
