# Round-robin pool for POST + default
upstream rr_pool {
    server ipfs-cluster-1.koneksi.co.kr:443 backup weight=1;
    #server ipfs-cluster-3.koneksi.co.kr:443 max_fails=3 fail_timeout=10s;
    server ipfs-cluster-4.koneksi.co.kr:443 max_fails=3 fail_timeout=10s;
    keepalive 64;
}

# GET pool: server1 active, server3/4 as backup (passive)
upstream get_pool {
    server ipfs-cluster-1.koneksi.co.kr:443 max_fails=3 fail_timeout=10s;
    #server ipfs-cluster-3.koneksi.co.kr:443 backup weight=1;
    server ipfs-cluster-4.koneksi.co.kr:443 backup weight=100;
    keepalive 64;
}